export const enum QUERIES {
	SIGN_IN = 'sign-in',
	SIGN_UP = 'sign-up',
	CHECK_VERIFY = 'check-verify',
	PROFILE = 'get-profile',
	LOGOUT = 'logout',
	GET_NOTE = 'get-note',
	GET_NOTES = 'get-notes',
	CREATE_NOTE = 'create-note',
	UPDATE_NOTE = 'update-note',
	DELETE_NOTE = 'delete-note',
	CREATE_CATEGORY = 'create-category',
	GET_CATEGORY = 'get-category',
	GET_CATEGORIES = 'get-categories',
	MOD_GET_CATEGORY = 'get-category-for-moderator',
	MOD_ACCEPT_NOTE_CHANGE = 'change-note-for-moderator',
	MOD_GET_NOTES = 'get-note-for-moderator',
	TOGGLE_ACTUAL_NOTE = 'toggle-actual-note',
	CHANGE_USER_PASSWORD = 'change-user-password',
	USEFUL_NOTE = 'useful-note',
	DIS_USEFUL_NOTE = 'dis-useful-note',
	NOTE_PINNED_TOGGLE = 'note-pinned-toggle',
}
