export const enum ROUTES {
	HOME = '/',
	AUTH = '/auth',
	VERIFY = '/verify/',
	CREATE_NOTE = '/create-note',
	NOTES = '/notes',
	NOTE = '/notes/',
	CATEGORIES = '/categories',
	CATEGORY = '/categories/',
	PDF_LIST = '/pdf-list',
	PDF_VIEW = '/pdf-list/',
	CREATE_CATEGORY = '/categories/create',
	MOD_PANEL = '/mod-panel',
	MOD_ACCEPT_NOTES = '/mod-panel/accept-or-decline/',
	PROFILE = '/profile',
	SETTINGS = PROFILE + '/settings',
}
